CREATE TABLE IF NOT EXISTS schema_versions (version integer PRIMARY KEY);
CREATE TABLE IF NOT EXISTS merchants (id text PRIMARY KEY, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS products (id text PRIMARY KEY, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS locations (id text PRIMARY KEY, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS destinations (id text PRIMARY KEY, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS quotes (id text PRIMARY KEY, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS policy_passages (id text PRIMARY KEY, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS buyer_orders (id text PRIMARY KEY, data jsonb NOT NULL, deadline timestamptz NOT NULL, fulfilled boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS return_cases (id text PRIMARY KEY, data jsonb NOT NULL, version integer NOT NULL DEFAULT 1, status text NOT NULL DEFAULT 'submitted', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reservations (id text PRIMARY KEY, case_id text NOT NULL REFERENCES return_cases(id), buyer_id text NOT NULL REFERENCES buyer_orders(id), version integer NOT NULL, status text NOT NULL, expires_at timestamptz NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS one_item ON reservations(case_id) WHERE status='active';
CREATE UNIQUE INDEX IF NOT EXISTS one_buyer ON reservations(buyer_id) WHERE status='active';
CREATE TABLE IF NOT EXISTS route_proposals (id text PRIMARY KEY, case_id text NOT NULL REFERENCES return_cases(id), case_version integer NOT NULL, policy_version text NOT NULL, destination_id text NOT NULL, data jsonb NOT NULL, status text NOT NULL DEFAULT 'pending');
CREATE UNIQUE INDEX IF NOT EXISTS one_pending_plan ON route_proposals(case_id) WHERE status='pending';
CREATE TABLE IF NOT EXISTS shipments (id text PRIMARY KEY, case_id text NOT NULL UNIQUE REFERENCES return_cases(id), proposal_id text NOT NULL UNIQUE REFERENCES route_proposals(id), approval_key text NOT NULL UNIQUE, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS case_events (id bigserial PRIMARY KEY, case_id text NOT NULL REFERENCES return_cases(id), version integer NOT NULL, actor text NOT NULL, type text NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS jobs (id bigserial PRIMARY KEY, case_id text NOT NULL REFERENCES return_cases(id), version integer NOT NULL, type text NOT NULL, status text NOT NULL DEFAULT 'pending', attempts integer NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(), lease_until timestamptz, error text, UNIQUE(case_id,version,type));
CREATE TABLE IF NOT EXISTS agent_sessions (case_id text REFERENCES return_cases(id), role text, data jsonb NOT NULL, PRIMARY KEY(case_id,role));
CREATE TABLE IF NOT EXISTS provider_calls (request_key text PRIMARY KEY, provider text NOT NULL, status text NOT NULL, data jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tool_results (request_key text PRIMARY KEY, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS worker_status (id integer PRIMARY KEY, updated_at timestamptz NOT NULL DEFAULT now(), data jsonb NOT NULL);
INSERT INTO schema_versions VALUES(1) ON CONFLICT DO NOTHING;
